// Generated by scripts/optimize-artwork.py. Vite gives every file a content hash.
const dark_hero_shapes_480 = new URL('../assets/artwork/dark-hero-shapes-480.webp', import.meta.url).href;
const dark_hero_shapes_960 = new URL('../assets/artwork/dark-hero-shapes-960.webp', import.meta.url).href;
const light_hero_shapes_480 = new URL('../assets/artwork/light-hero-shapes-480.webp', import.meta.url).href;
const light_hero_shapes_960 = new URL('../assets/artwork/light-hero-shapes-960.webp', import.meta.url).href;
const dark_opora_logo_384 = new URL('../assets/artwork/dark-opora-logo-384.webp', import.meta.url).href;
const dark_opora_logo_768 = new URL('../assets/artwork/dark-opora-logo-768.webp', import.meta.url).href;
const light_opora_logo_384 = new URL('../assets/artwork/light-opora-logo-384.webp', import.meta.url).href;
const light_opora_logo_768 = new URL('../assets/artwork/light-opora-logo-768.webp', import.meta.url).href;
const dark_document_240 = new URL('../assets/artwork/dark-document-240.webp', import.meta.url).href;
const dark_document_480 = new URL('../assets/artwork/dark-document-480.webp', import.meta.url).href;
const light_document_240 = new URL('../assets/artwork/light-document-240.webp', import.meta.url).href;
const light_document_480 = new URL('../assets/artwork/light-document-480.webp', import.meta.url).href;
const dark_briefcase_240 = new URL('../assets/artwork/dark-briefcase-240.webp', import.meta.url).href;
const dark_briefcase_480 = new URL('../assets/artwork/dark-briefcase-480.webp', import.meta.url).href;
const light_briefcase_240 = new URL('../assets/artwork/light-briefcase-240.webp', import.meta.url).href;
const light_briefcase_480 = new URL('../assets/artwork/light-briefcase-480.webp', import.meta.url).href;
const dark_orb_160 = new URL('../assets/artwork/dark-orb-160.webp', import.meta.url).href;
const dark_orb_320 = new URL('../assets/artwork/dark-orb-320.webp', import.meta.url).href;
const light_orb_160 = new URL('../assets/artwork/light-orb-160.webp', import.meta.url).href;
const light_orb_320 = new URL('../assets/artwork/light-orb-320.webp', import.meta.url).href;
const dark_ring_240 = new URL('../assets/artwork/dark-ring-240.webp', import.meta.url).href;
const dark_ring_480 = new URL('../assets/artwork/dark-ring-480.webp', import.meta.url).href;
const light_ring_240 = new URL('../assets/artwork/light-ring-240.webp', import.meta.url).href;
const light_ring_480 = new URL('../assets/artwork/light-ring-480.webp', import.meta.url).href;
const dark_loop_240 = new URL('../assets/artwork/dark-loop-240.webp', import.meta.url).href;
const dark_loop_480 = new URL('../assets/artwork/dark-loop-480.webp', import.meta.url).href;
const light_loop_240 = new URL('../assets/artwork/light-loop-240.webp', import.meta.url).href;
const light_loop_480 = new URL('../assets/artwork/light-loop-480.webp', import.meta.url).href;
const dark_tiles_240 = new URL('../assets/artwork/dark-tiles-240.webp', import.meta.url).href;
const dark_tiles_480 = new URL('../assets/artwork/dark-tiles-480.webp', import.meta.url).href;
const light_tiles_240 = new URL('../assets/artwork/light-tiles-240.webp', import.meta.url).href;
const light_tiles_480 = new URL('../assets/artwork/light-tiles-480.webp', import.meta.url).href;

type Variant = { src: string; srcSet: string };
export const artwork: Record<string, { sizes: string; light: Variant; dark: Variant }> = {
  '/assets/hero-shapes.png': {
    sizes: '318px',
    dark: { src: dark_hero_shapes_960, srcSet: `${dark_hero_shapes_480} 480w, ${dark_hero_shapes_960} 960w` },
    light: { src: light_hero_shapes_960, srcSet: `${light_hero_shapes_480} 480w, ${light_hero_shapes_960} 960w` },
  },
  '/assets/opora-logo.png': {
    sizes: '260px',
    dark: { src: dark_opora_logo_768, srcSet: `${dark_opora_logo_384} 384w, ${dark_opora_logo_768} 768w` },
    light: { src: light_opora_logo_768, srcSet: `${light_opora_logo_384} 384w, ${light_opora_logo_768} 768w` },
  },
  '/assets/document.png': {
    sizes: '165px',
    dark: { src: dark_document_480, srcSet: `${dark_document_240} 240w, ${dark_document_480} 480w` },
    light: { src: light_document_480, srcSet: `${light_document_240} 240w, ${light_document_480} 480w` },
  },
  '/assets/briefcase.png': {
    sizes: '130px',
    dark: { src: dark_briefcase_480, srcSet: `${dark_briefcase_240} 240w, ${dark_briefcase_480} 480w` },
    light: { src: light_briefcase_480, srcSet: `${light_briefcase_240} 240w, ${light_briefcase_480} 480w` },
  },
  '/assets/orb.png': {
    sizes: '100px',
    dark: { src: dark_orb_320, srcSet: `${dark_orb_160} 160w, ${dark_orb_320} 320w` },
    light: { src: light_orb_320, srcSet: `${light_orb_160} 160w, ${light_orb_320} 320w` },
  },
  '/assets/glass/ring.png': {
    sizes: '150px',
    dark: { src: dark_ring_480, srcSet: `${dark_ring_240} 240w, ${dark_ring_480} 480w` },
    light: { src: light_ring_480, srcSet: `${light_ring_240} 240w, ${light_ring_480} 480w` },
  },
  '/assets/glass/loop.png': {
    sizes: '150px',
    dark: { src: dark_loop_480, srcSet: `${dark_loop_240} 240w, ${dark_loop_480} 480w` },
    light: { src: light_loop_480, srcSet: `${light_loop_240} 240w, ${light_loop_480} 480w` },
  },
  '/assets/glass/tiles.png': {
    sizes: '150px',
    dark: { src: dark_tiles_480, srcSet: `${dark_tiles_240} 240w, ${dark_tiles_480} 480w` },
    light: { src: light_tiles_480, srcSet: `${light_tiles_240} 240w, ${light_tiles_480} 480w` },
  },
};
