"""Rebuild committed mobile WebP exports: python -m pip install Pillow==12.3.0."""
from pathlib import Path
from PIL import Image
import json

root = Path(__file__).resolve().parents[1]
target = root / 'src/assets/artwork'
target.mkdir(parents=True, exist_ok=True)
specs = {
    'hero-shapes': ('hero-shapes.png', [480, 960], 318),
    'opora-logo': ('opora-logo.png', [384, 768], 260),
    'document': ('document.png', [240, 480], 165),
    'briefcase': ('briefcase.png', [240, 480], 130),
    'orb': ('orb.png', [160, 320], 100),
    'ring': ('glass/ring.png', [240, 480], 150),
    'loop': ('glass/loop.png', [240, 480], 150),
    'tiles': ('glass/tiles.png', [240, 480], 150),
}
imports, entries, report = [], [], []
for name, (source, widths, size) in specs.items():
    themes = []
    for theme in ['dark', 'light']:
        original = root / 'public/assets' / (source if theme == 'dark' else f'light/neutral/{name}.webp')
        image = Image.open(original).convert('RGBA')
        variants = []
        for width in widths:
            filename = f'{theme}-{name}-{width}.webp'
            output = target / filename
            resized = image.resize((width, round(image.height * width / image.width)), Image.Resampling.LANCZOS)
            resized.save(output, 'WEBP', quality=86, method=6, alpha_quality=100)
            assert Image.open(output).getchannel('A').tobytes() == resized.getchannel('A').tobytes()
            symbol = f'{theme}_{name.replace("-", "_")}_{width}'
            imports.append(f"const {symbol} = new URL('../assets/artwork/{filename}', import.meta.url).href;")
            variants.append((width, symbol))
            report.append({'source': str(original.relative_to(root)), 'file': filename,
                           'originalBytes': original.stat().st_size, 'bytes': output.stat().st_size})
        srcset = ', '.join('${' + symbol + '} ' + str(width) + 'w' for width, symbol in variants)
        themes.append(f"    {theme}: {{ src: {variants[-1][1]}, srcSet: `{srcset}` }},")
    entries.append(f"  '/assets/{source}': {{\n    sizes: '{size}px',\n" + '\n'.join(themes) + '\n  },')
manifest = '// Generated by scripts/optimize-artwork.py. Vite gives every file a content hash.\n'
manifest += '\n'.join(imports) + '\n\ntype Variant = { src: string; srcSet: string };\n'
manifest += 'export const artwork: Record<string, { sizes: string; light: Variant; dark: Variant }> = {\n'
manifest += '\n'.join(entries) + '\n};\n'
(root / 'src/business/artwork.ts').write_text(manifest, encoding='utf-8')
(target / 'sizes.json').write_text(json.dumps(report, indent=2) + '\n', encoding='utf-8')
for row in report:
    print(row['file'], row['bytes'])
